// ConcealLock.js
import React, { useState } from 'react';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Image from 'react-bootstrap/Image';
import Pagination from 'react-bootstrap/Pagination';
import { FaStar, FaMoneyBill, FaTimes } from 'react-icons/fa';
import { Link } from 'react-router-dom';
// import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Modal from 'react-bootstrap/Modal';
import Logo from './logo.png';
import Button from 'react-bootstrap/Button';
import { Navbar} from 'react-bootstrap';

import { Alert } from 'react-bootstrap';
import { ToastContainer, toast } from 'react-bootstrap';


import './ProductDetails.css'

import { useQuote } from './QuoteContext';

const products = [
  { name: 'EAGLE E7 (BLACK)', 
  Original_Price:'25.00', 
  Discounted_Price: '24.00', 
  var_total_price:'10000', 
  var_tdis_price: '9600', 
  MOQ: '400PC', 
  image: "/83.jpg", 
  rating: 4.8, 
  rate: 10, 
  CODE : 'GT-201',
  info:'GT-201 # EAGLE E7 ( 4 " SEMI METAL LOCK ) 4" ALUMINUM BODY WITH PRIMIUM NYLONE RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[ 
    { var_code: 'GT-201-BL', 
    var_name: 'EAGLE - E7 (BLACK)', 
    var_img: '40.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600', 
    Original_Price:'25.00', 
    Discounted_Price: '24.00',
    var_color: 'BLACK' },
    { var_code: 'GT-201-BR', 
    var_name: 'EAGLE - E7 (BROWN)', 
    var_img: '41.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600', 
    Original_Price:'25.00', 
    Discounted_Price: '24.00',
    var_color: 'BROWN' }, 
    { var_code: 'GT-201-IV', 
    var_name: 'EAGLE - E7 ( IVORY )', 
    var_img: '1.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600', 
    Original_Price:'25.00', 
    Discounted_Price: '24.00',
    var_color: 'IVORY' }, 
    { var_code: 'GT-201-WT', 
    var_name: 'EAGLE - E7 ( WHITE )', 
    var_img: '43.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600', 
    Original_Price:'25.00', 
    Discounted_Price: '24.00',
    var_color: 'WHITE' }, 
    { var_code: 'GT-201-SI', 
    var_name: 'EAGLE - E7 ( SILVER )', 
    var_img: '44.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600',
    Original_Price:'25.00', 
    Discounted_Price: '24.00', 
    var_color: 'SILVER' }, 
    { var_code: 'GT-201-GL', 
    var_name: 'EAGLE - E7 ( GOLDEN )', 
    var_img: '45.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600', 
    Original_Price:'25.00', 
    Discounted_Price: '24.00',
    var_color: 'GOLDEN' }, 
    { var_code: 'GT-201-DR', 
    var_name: 'EAGLE - E7 ( DORANDO )', 
    var_img: '46.jpg',
    var_moq:'400',
    var_total_price:'10000', 
    var_tdis_price: '9600',
    Original_Price:'25.00', 
    Discounted_Price: '24.00', 
    var_color: 'DORANDO' },
  ]
},
  { name: 'EAGLE E9', 
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'11200', 
  var_tdis_price: '11000',  
  MOQ: '200PC', 
  image: "/84.jpg", 
  rating: 4.8, 
  rate: 20, 
  CODE : 'GT-202',
  info:'GT-202 # EAGLE E9 ( 4 " FULL METAL LOCK )  4" ALUMINUM BODY WITH ALUMINUM CASTING RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[ 
    { var_code: 'GT-202-BL', 
    var_name: 'EAGLE - E9', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000',
    Original_Price:'56.00', 
    Discounted_Price: '55.00',  
    var_color: 'BLACK' 
  },
    { var_code: 'GT-202-BR', 
    var_name: 'EAGLE - E9', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000', 
    Original_Price:'56.00', 
    Discounted_Price: '55.00', 
    var_color: 'BROWN' 
  },
    { var_code: 'GT-202-IV', 
    var_name: 'EAGLE - E9 ( IVORY )', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000', 
    Original_Price:'56.00', 
    Discounted_Price: '55.00', 
    var_color: 'IVORY' 
  },
    { var_code: 'GT-202-WT', 
    var_name: 'EAGLE - E9 ( WHITE )', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000',
    Original_Price:'56.00', 
    Discounted_Price: '55.00',  
    var_color: 'WHITE' 
  },
    { var_code: 'GT-202-SI', 
    var_name: 'EAGLE - E9 ( SILVER )', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000', 
    Original_Price:'56.00', 
    Discounted_Price: '55.00', 
    var_color: 'SILVER' 
  }, 
    { var_code: 'GT-202-GL', 
    var_name: 'EAGLE - E9 ( GOLDEN )', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000', 
    Original_Price:'56.00', 
    Discounted_Price: '55.00', 
    var_color: 'GOLDEN' 
  }, 
    { var_code: 'GT-202-DR', 
    var_name: 'EAGLE - E9 ( DORANDO )', 
    var_img: '1.jpg',
    var_moq:'200',
    var_total_price:'11200', 
    var_tdis_price: '11000',
    Original_Price:'56.00', 
    Discounted_Price: '55.00',  
    var_color: 'DORANDO' 
  },
  ]
},
  {  name: ' EAGLE 81', 
    Original_Price:'56.00', 
    Discounted_Price: '55.00', 
    var_total_price:'11200', 
    var_tdis_price: '11000', 
    MOQ: '200PC', 
    image: "/90.jpg", 
    rating: 4.8, 
    rate: 30, 
    CODE : 'GT-203',
    info:'GT-203 # EAGLE 81 ( 6 " SEMI METAL LOCK )  6" ALUMINUM BODY WITH PRIMIUM NYLONE RECIVERT COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
    variant:[
      { var_code: 'GT-203-BL', 
      var_name: 'EAGLE - E81', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000',
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00',  
      var_color: 'BLACK' 
    }, 
      { var_code: 'GT-203-BR',
      var_name: 'EAGLE - E81', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000', 
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00', 
      var_color: 'BROWN' 
    }, 
      { var_code: 'GT-203-IV', 
      var_name: 'EAGLE - E81 ( IVORY )', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000', 
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00', 
      var_color: 'IVORY' 
    }, 
      { var_code: 'GT-203-WT', 
      var_name: 'EAGLE - E81 ( WHITE )', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000', 
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00', 
      var_color: 'WHITE' 
    }, 
      { var_code: 'GT-203-SI', 
      var_name: 'EAGLE - E81 ( SILVER )', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000', 
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00', 
      var_color: 'SILVER' 
    }, 
      { var_code: 'GT-203-GL', 
      var_name: 'EAGLE - E81 ( GOLDEN )', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000', 
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00', 
      var_color: 'GOLDEN' 
    }, 
      { var_code: 'GT-203-DR', 
      var_name: 'EAGLE - E81 ( DORANDO )', 
      var_img: '1.jpg',
      var_total_price:'11200', 
      var_tdis_price: '11000',
      var_moq: '200PC',
      Original_Price:'56.00', 
      Discounted_Price: '55.00',  
      var_color: 'DORANDO' 
    },
    ]
  },
  { name: ' EAGLE 82', 
  Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000', 
  MOQ: '200 pc', 
  image: "/86.jpg", 
  rating: 4.8, 
  rate: 50, 
  CODE : 'GT-204',
  info:'GT-204 # EAGLE 82 ( 6 " FULL METAL LOCK )  6" ALUMINUM BODY WITH PRIMIUM CASTING RECIVERT COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-204-BL', 
    var_name: 'EAGLE - E82 ( BLACK )', 
    var_img: '1.jpg',
    Original_Price:'88.00', 
    Discounted_Price: '85.00', 
    var_total_price:'17600', 
    var_tdis_price: '17000', 
    var_color: 'BLACK' 
  },
  { var_code: 'GT-204-BR', 
  var_name: 'EAGLE - E82 ( BROWN )', 
  var_img: '1.jpg',
    Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
  var_color: 'BROWN'
 },
 { var_code: 'GT-204-IV', 
 var_name: 'EAGLE - E82 ( IVORY )', 
 var_img: '1.jpg',
   Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
 var_color: 'IVORY' 
},
{ var_code: 'GT-204-WT', 
var_name: 'EAGLE - E82 ( WHITE )', 
var_img: '1.jpg',
  Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
var_color: 'WHITE' 
},
{ var_code: 'GT-204-SI', 
var_name: 'EAGLE - E82 ( SILVER )', 
var_img: '1.jpg',
  Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
var_color: 'SILVER' 
},
{ var_code: 'GT-204-GL', 
var_name: 'EAGLE - E82 ( GOLDEN )', 
var_img: '1.jpg',
  Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
var_color: 'GOLDEN' 
},
{ var_code: 'GT-204-DR', 
var_name: 'EAGLE - E82 ( DORANDO )', 
var_img: '1.jpg',
  Original_Price:'88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',  
var_color: 'DORANDO' 
}
],
},
  { name: ' EAGLE 88', 
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000', 
  MOQ: '200 pc', 
  image: "/87.jpg", 
  rating: 4.8, 
  rate: 20, 
  CODE : 'GT-205',
  info:'GT-205 # EAGLE 88 ( 6 " INDIAN DOMAL  LOCK ) 6" ALUMINUM BODY WITH PRIMIUM NYLONE RECIVERT COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-205-BL', 
    var_name: 'EAGLE - E88', 
    var_img: '1.jpg',
     Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
    var_color: 'BLACK' 
  },
  { var_code: 'GT-205-BR', 
  var_name: 'EAGLE - E88', 
  var_img: '1.jpg',
   Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
  var_color: 'BROWN' 
},
{ var_code: 'GT-205-IV', 
var_name: 'EAGLE - E88 (IVORY)', 
var_img: '1.jpg',
 Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
var_color: 'IVORY' 
},
{ var_code: 'GT-205-WT', 
var_name: 'EAGLE - E88 (WHITE)', 
var_img: '1.jpg',
 Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
var_color: 'WHITE' 
},
{ var_code: 'GT-205-SI', 
var_name: 'EAGLE - E88 (SILVER)', 
var_img: '1.jpg',
 Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
var_color: 'SILVER' 
},
{ var_code: 'GT-205-GL', 
var_name: 'EAGLE - E88 (GOLDEN)', 
var_img: '1.jpg',
 Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
var_color: 'GOLDEN' 
},
{ var_code: 'GT-205-DR', 
var_name: 'EAGLE - E88 (DORANDO)', 
var_img: '1.jpg',
 Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'11200', 
  var_tdis_price: '11000',
  var_moq: '200PC',  
var_color: 'DORANDO' 
},
]
},
  { name: 'TAIWAN HANDEL(6")', 
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
  MOQ: '192PC', 
  image: "/88.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-206',
  info:'GT-206 # TAIWAN HANDEL ( 6" ) HANDEL WITH ALUMINUM BODY COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-206-BL', 
    var_name: 'TAIWAN HANDEL 6"', 
    var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
  var_moq: '192PC',
  var_color: 'BLACK' 
  },
  { var_code: 'GT-206-BR', 
  var_name: 'TAIWAN HANDEL 6"', 
  var_img: '1.jpg',
    Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
  var_moq: '192PC',
  var_color: 'BROWN' 
},
{ var_code: 'GT-206-IV', 
var_name: 'TAIWAN HANDEL 6" (IVORY)', 
var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
var_moq: '192PC',
var_color: 'IVORY' 
},
{ var_code: 'GT-206-WT', 
var_name: 'TAIWAN HANDEL 6" (WHITE)', 
var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
var_moq: '192PC',
var_color: 'WHITE' 
},
{ var_code: 'GT-206-SI', 
var_name: 'TAIWAN HANDEL 6" (SILVER)', 
var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
var_moq: '192PC',
var_color: 'SILVER' 
},
{ var_code: 'GT-206-GL', 
var_name: 'TAIWAN HANDEL 6" (GOLDEN)', 
var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
var_moq: '192PC',
var_color: 'GOLDEN' 
},
{ var_code: 'GT-206-DR', 
var_name: 'TAIWAN HANDEL 6" (DORANDO)', 
var_img: '1.jpg',
  Original_Price:'42.00', 
  Discounted_Price: '40.00', 
  var_total_price:'8064', 
  var_tdis_price: '7680', 
var_moq: '192PC',
var_color: 'DORANDO' 
},
]
},
  { name: ' TAIWAN HANDEL(8")', 
  Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
  MOQ: '192 pc', 
  image: "/1.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-207',
  info:'GT-207 # TAIWAN HANDEL ( 8" ) HANDEL WITH ALUMINUM BODY COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO',  
  variant:[
    { var_code: 'GT-207-BL', 
    var_name: 'TAIWAN HANDEL 8"', 
    var_img: '1.jpg',  
    Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640',
    var_moq: '192PC',
    var_color: 'BLACK' 
  },
    { var_code: 'GT-207-BR', 
    var_name: 'TAIWAN HANDEL 8"', 
    var_img: '1.jpg',
      Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
var_moq: '192PC',
    var_color: 'BROWN' 
  },
  { var_code: 'GT-207-IV', 
  var_name: 'TAIWAN HANDEL 8" (IVORY)', 
  var_img: '1.jpg',
    Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
    var_moq: '192PC',
  var_color: 'IVORY' 
},
{ var_code: 'GT-207-WT', 
var_name: 'TAIWAN HANDEL 8" (WHITE)', 
var_img: '1.jpg',
  Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
    var_moq: '192PC',
 var_color: 'WHITE' 
},
{ var_code: 'GT-207-SI', 
var_name: 'TAIWAN HANDEL 8" (SILVER)', 
var_img: '1.jpg',
  Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
    var_moq: '192PC',
var_color: 'SILVER' 
},
{ var_code: 'GT-207-GL', 
var_name: 'TAIWAN HANDEL 8" (GOLDEN)', 
var_img: '1.jpg',
  Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
    var_moq: '192PC',
var_color: 'GOLDEN' 
},
{ var_code: 'GT-207-DR', 
var_name: 'TAIWAN HANDEL 8" (DORANDO)', 
var_img: '1.jpg',
  Original_Price:'48.00', 
  Discounted_Price: '45.00', 
  var_total_price:'9216', 
    var_tdis_price: '8640', 
    var_moq: '192PC',
var_color: 'DORANDO' },
]
},
  { name: ' SAILESH LOCK(4") ', 
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  MOQ: '480 pc', 
  image: "/36.jpg", 
  rating: 4.8, 
  rate: 90, 
  CODE : 'GT-208',
  info:'GT-208 # SAILESH LOCK ( 4" ) ALUMINUM BODY WITH METAL RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-208-BL', 
    var_name: 'SAILESH LOCK 4"', 
    var_img: '1.jpg',
      Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
    var_color: 'BLACK' 
  },
  { var_code: 'GT-208-BR', 
  var_name: 'SAILESH LOCK 4"', 
  var_img: '1.jpg',
    Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
  var_color: 'BROWN' 
},
{ var_code: 'GT-208-IV', 
var_name: 'SAILESH LOCK 4" (IVORY)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
var_color: 'IVORY' 
},
{ var_code: 'GT-208-WT', 
var_name: 'SAILESH LOCK 4" (WHITE)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
var_color: 'WHITE' 
},
{ var_code: 'GT-208-SI', 
var_name: 'SAILESH LOCK 4" (SILVER)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
var_color: 'SILVER' },
{ var_code: 'GT-208-GL', 
var_name: 'SAILESH LOCK 4" (GOLDEN)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
var_color: 'GOLDEN' 
},
{ var_code: 'GT-208-DR', 
var_name: 'SAILESH LOCK 4" (DORANDO)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00',
  var_total_price:'14400', 
    var_tdis_price: '13680',  
  var_moq: '480PC', 
var_color: 'DORANDO' },
]
},
  { name: 'STAR LOCK(44 NO)', 
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
MOQ: '240 pc', 
  image: "/37.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-209',
  info:'GT-209 #STAR LOCK ( 44 NO ) ALUMINUM BODY WITH METAL RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO',  
  variant:[
    { var_code: 'GT-209-BL', 
    var_name: 'SAILESH LOCK 6"', 
    var_img: '1.jpg',
      Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
    var_color: 'BLACK' 
  },
  { var_code: 'GT-209-BR', 
  var_name: 'SAILESH LOCK 6"', 
  var_img: '1.jpg',
    Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
  var_color: 'BROWN' 
},
{ var_code: 'GT-209-IV', 
var_name: 'SAILESH LOCK 6" (IVORY)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
var_color: 'IVORY' 
},
{ var_code: 'GT-209-WT', 
var_name: 'SAILESH LOCK 6" (WHITE)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
var_color: 'WHITE' }
,{ var_code: 'GT-209-SI', 
var_name: 'SAILESH LOCK 6" (SILVER)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
var_color: 'SILVER' },
{ var_code: 'GT-209-GL', 
var_name: 'SAILESH LOCK 6" (GOLDEN)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
var_color: 'GOLDEN' 
},
{ var_code: 'GT-209-DR', 
var_name: 'SAILESH LOCK 6" (DORANDO)', 
var_img: '1.jpg',
  Original_Price:'56.00', 
  Discounted_Price: '55.00', 
  var_total_price:'13440', 
  var_tdis_price: '13200',
var_moq: '240PC',  
var_color: 'DORANDO' },
]
},
  { name: ' MARUTI LOCK 4"(SILVER)', 
  Original_Price:'11.00', 
  Discounted_Price: '10.50', 
  var_total_price:'22000', 
  var_tdis_price: '21000',
MOQ: '2000 pc', 
image: "/46.jpg", 
  rating: 4.8, 
  rate: 100, 
  CODE : 'GT-210',
  info:'GT-210 # MARUTI LOCK 4" ( SILVER ) ALUMINUM BODY SIZE 4"C ( 1000 SET )  COLOUR : MET', 
  variant:[
    { var_code: 'GT-210-SI', 
    var_name: 'MARUTI LOCK 4" (SILVER)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'22000', 
    var_tdis_price: '21000',
    var_moq: '2000PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-210-BL', 
    var_name: 'MARUTI LOCK 4" (BLACK)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-210-BR', 
    var_name: 'MARUTI LOCK 4" (BROWN)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-210-IV', 
    var_name: 'MARUTI LOCK 4" (IVORY)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-210-WT', 
    var_name: 'MARUTI LOCK 4" (WHITE)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC', 
    var_color: 'WHITE' },
    { var_code: 'GT-210-GL', 
    var_name: 'MARUTI LOCK 4" (GOLDEN)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-210-DR', 
    var_name: 'MARUTI LOCK 4" (DORANDO)', 
    var_img: '1.jpg',
    Original_Price:'11.00', 
    Discounted_Price: '10.50', 
    var_total_price:'24000', 
    var_tdis_price: '23000',
    var_moq: '2000PC',  
    var_color: 'DORANDO' },
  ]},
  { name: ' STAR LOCK (44 NO )', 
  Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
MOQ: '400 pc', 
image: "/47.jpg", 
  rating: 4.8, 
  rate: 10, 
  CODE : 'GT-211',
  info:'GT-211 # STAR LOCK ( 44 NO ) ALUMINUM 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO' , 
  variant:[
    { var_code: 'GT-211-BL', 
    var_name: 'STAR LOCK (44 NO) (BLACK)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc', 
    var_color: 'BLACK' },
    { var_code: 'GT-211-BR', 
    var_name: 'STAR LOCK (44 NO) (BROWN)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'BROWN' },
    { var_code: 'GT-211-IV', 
    var_name: 'STAR LOCK (44 NO) (IVORY)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'IVORY' },
    { var_code: 'GT-211-WT', 
    var_name: 'STAR LOCK (44 NO) (WHITE)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'WHITE' },
    { var_code: 'GT-211-SI', 
    var_name: 'STAR LOCK (44 NO) (SILVER)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'SILVER' },
    { var_code: 'GT-211-GL', 
    var_name: 'STAR LOCK (44 NO) (GOLDEN)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-211-DR', 
    var_name: 'STAR LOCK (44 NO) (DORANDO)', 
    var_img: '1.jpg',
     Original_Price:'30.00', 
  Discounted_Price: '29.00', 
  var_total_price:'12000', 
  var_tdis_price: '11800',
var_moq: '400 pc',  
    var_color: 'DORANDO' },
  ]},
  { name: 'STAR LOCK (74 NO )', 
  Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
MOQ: '400 pc', 
image: "/48.jpg", 
  rating: 4.8, 
  rate: 20, 
  CODE : 'GT-212',
  info:'GT-212 #STAR LOCK ( 74 NO ) ZINK 4" BODY WITH FIBER RECIVERCOLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO ', 
  variant:[
    { var_code: 'GT-212-BL', 
    var_name: 'STAR LOCK (74 NO) (BLACK)', 
    var_img: '1.jpg',
    Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-212-BR', 
    var_name: 'STAR LOCK (74 NO) (BROWN)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-212-IV', 
    var_name: 'STAR LOCK (74 NO) (IVORY)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-212-WT', 
    var_name: 'STAR LOCK (74 NO) (WHITE)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-212-SI', 
    var_name: 'STAR LOCK (74 NO) (SILVER)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-212-GL', 
    var_name: 'STAR LOCK (74 NO) (GOLDEN)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-212-DR', 
    var_name: 'STAR LOCK (74 NO) (DORANDO)', 
    var_img: '1.jpg',
      Original_Price:'41.00', 
  Discounted_Price: '40.00', 
  var_total_price:'16400', 
  var_tdis_price: '16200',
var_moq: '400PC',  
    var_color: 'DORANDO' },
  ]},
  { name: 'STAR LOCK (75 NO )', 
  Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
MOQ: '400PC', 
image: "/52.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-213',
  info:'GT-213 #STAR LOCK ( 75 NO ) FIBER 4" BODY WITH FIBER RECIVER  COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-213-BL', 
    var_name: 'STAR LOCK (75 NO) (BLACK)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-213-BR', 
    var_name: 'STAR LOCK (75 NO) (BROWN)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-213-IV', 
    var_name: 'STAR LOCK (75 NO) (IVORY)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-213-WT', 
    var_name: 'STAR LOCK (75 NO) (WHITE)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-213-SI', 
    var_name: 'STAR LOCK (75 NO) (SILVER)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-213-GL', 
    var_name: 'STAR LOCK (75 NO) (GOLDEN)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-213-DR', 
    var_name: 'STAR LOCK (75 NO) (DORANDO)', 
    var_img: '1.jpg',
      Original_Price:'17.50', 
  Discounted_Price: '16.50', 
  var_total_price:'7000', 
  var_tdis_price: '6600',
var_moq: '400PC',  
    var_color: 'DORANDO' },
  ]},
  { name: 'STAR LOCK (49 NO )', 
  Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
MOQ: '400PC', 
image: "/76.jpg", 
  rating: 4.8, 
  rate: 50, 
  CODE : 'GT-214',
  info:'GT-214 #STAR LOCK ( 49 NO ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-214-BL', 
    var_name: 'STAR LOCK (49 NO) (BLACK)', 
    var_img: '1.jpg',
     Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',
    var_color: 'BLACK' },
    { var_code: 'GT-214-BR', 
    var_name: 'STAR LOCK (49 NO) (BROWN)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-214-IV', 
    var_name: 'STAR LOCK (49 NO) (IVORY)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-214-WT', 
    var_name: 'STAR LOCK (49 NO) (WHITE)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-214-SI', 
    var_name: 'STAR LOCK (49 NO) (SILVER)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-214-GL', 
    var_name: 'STAR LOCK (49 NO) (GOLDEN)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-214-DR', 
    var_name: 'STAR LOCK (49 NO) (DORANDO)', 
    var_img: '1.jpg',
      Original_Price:'28.00', 
  Discounted_Price: '27.00', 
  var_total_price:'11200', 
  var_tdis_price: '10800',
var_moq: '400PC',  
    var_color: 'DORANDO' },
  ]},
  { name: 'STAR LOCK (55 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
MOQ: '400 pc', 
image: "/89.jpg", 
  rating: 4.8, 
  rate: 20, 
  CODE : 'GT-215',
  info:'GT-215 #STAR LOCK ( 55 NO ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO' , 
  variant:[
    { var_code: 'GT-215-BL', 
    var_name: 'STAR LOCK (55 NO) (BLACK)', 
    var_img: '1.jpg',
Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',
    var_color: 'BLACK' },
    { var_code: 'GT-215-BR', 
    var_name: 'STAR LOCK (55 NO) (BROWN)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'BROWN' },
    { var_code: 'GT-215-IV', 
    var_name: 'STAR LOCK (55 NO) (IVORY)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'IVORY' },
    { var_code: 'GT-215-WT', 
    var_name: 'STAR LOCK (55 NO) (WHITE)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'WHITE' },
    { var_code: 'GT-215-SI', 
    var_name: 'STAR LOCK (55 NO) (SILVER)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'SILVER' },
    { var_code: 'GT-215-GL', 
    var_name: 'STAR LOCK (55 NO) (GOLDEN)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-215-DR', 
    var_name: 'STAR LOCK (55 NO) (DORANDO)', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '400 pc',  
    var_color: 'DORANDO' },
  ]},
  { name: 'STAR LOCK (71 NO ) ', 
  Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  MOQ: '200PC', 
  image: "/90.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-216',
  info:'GT-216 #STAR LOCK ( 71 NO )  6" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-216-BL', 
    var_name: 'STAR LOCK (71 NO) (BLACK)', 
    var_img: '1.jpg',
    Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',
    var_color: 'BLACK' },
    { var_code: 'GT-216-BR', 
    var_name: 'STAR LOCK (71 NO) (BROWN)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-216-IV', 
    var_name: 'STAR LOCK (71 NO) (IVORY)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-216-WT', 
    var_name: 'STAR LOCK (71 NO) (WHITE)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-216-SI', 
    var_name: 'STAR LOCK (71 NO) (SILVER)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-216-GL', 
    var_name: 'STAR LOCK (71 NO) (GOLDEN)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-216-DR', 
    var_name: 'STAR LOCK (71 NO) (DORANDO)', 
    var_img: '1.jpg',
      Original_Price:'124.00', 
  Discounted_Price: '122.0',
   var_total_price:'24800', 
  var_tdis_price: '24400',   
  var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: 'STAR LOCK (73 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
MOQ: '200PC', 
image: "/100.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-217',
  info:'GT-217 #STAR LOCK ( 73 NO )  FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-217-BL', 
    var_name: 'STAR LOCK ( 73 NO ) ( BLACK )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',
    var_color: 'BLACK' },
    { var_code: 'GT-217-BR', 
    var_name: 'STAR LOCK ( 73 NO ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-217-IV', 
    var_name: 'STAR LOCK ( 73 NO ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-217-WT', 
    var_name: 'STAR LOCK ( 73 NO ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-217-SI', 
    var_name: 'STAR LOCK ( 73 NO ) ( SILVER )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-217-GL', 
    var_name: 'STAR LOCK ( 73 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-217-DR', 
    var_name: 'STAR LOCK ( 73 NO ) ( DORANDO )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: 'STAR LOCK (73 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
MOQ: '200PC', 
  image: "/91.jpg", 
  rating: 4.8, 
  rate: 90, 
  CODE : 'GT-218',
  info:'GT-218 #STAR LOCK ( 73 NO ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-218-BL', 
    var_name: 'STAR LOCK ( 73 NO ) ( BLACK )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-218-BR', 
    var_name: 'STAR LOCK ( 73 NO ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-218-IV', 
    var_name: 'STAR LOCK ( 73 NO ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-218-WT', 
    var_name: 'STAR LOCK ( 73 NO ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-218-SI', 
    var_name: 'STAR LOCK ( 73 NO ) ( SILVER )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-218-GL', 
    var_name: 'STAR LOCK ( 73 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-218-DR', 
    var_name: 'STAR LOCK ( 73 NO ) ( DORANDO )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: ' ALBOSE (85 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
MOQ: '200PC', 
  image: "/92.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-219',
  info:'GT-219 # ALBOSE ( 85 NO )  FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-219-BL',
    var_name: 'ALBOSE ( 85 NO ) ( BLACK )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'BLACK' },
    { var_code: 'GT-219-BR', 
    var_name: 'ALBOSE ( 85 NO ) ( BROWN )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'BROWN' },
    { var_code: 'GT-219-IV', 
    var_name: 'ALBOSE ( 85 NO ) ( IVORY )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'IVORY' },
    { var_code: 'GT-219-WT', 
    var_name: 'ALBOSE ( 85 NO ) ( WHITE )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'WHITE' },
    { var_code: 'GT-219-SI', 
    var_name: 'ALBOSE ( 85 NO ) ( SILVER )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'SILVER' },
    { var_code: 'GT-219-GL', 
    var_name: 'ALBOSE ( 85 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'GOLDEN' },
    { var_code: 'GT-219-DR', 
    var_name: 'ALBOSE ( 85 NO ) ( DORANDO )', 
    var_img: '1.jpg',
       Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'10800', 
  var_tdis_price: '10400',
var_moq: '200PC',   
    var_color: 'DORANDO' }]
  },
  { name: ' ALBOSE (84 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC', 
  image: "/92.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-220',
  info:'FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-220-BL', 
    var_name: 'ALBOSE ( 84 NO ) ( BLACK )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-220-BR', 
    var_name: 'ALBOSE ( 84 NO ) ( BROWN )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'BROWN' },
    { var_code: 'GT-220-IV', 
    var_name: 'ALBOSE ( 84 NO ) ( IVORY )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'IVORY' },
    { var_code: 'GT-220-WT', 
    var_name: 'ALBOSE ( 84 NO ) ( WHITE )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'WHITE' },
    { var_code: 'GT-220-SI', 
    var_name: 'ALBOSE ( 84 NO ) ( SILVER )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'SILVER' },
    { var_code: 'GT-220-GL', 
    var_name: 'ALBOSE ( 84 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'GOLDEN' },
    { var_code: 'GT-220-DR', 
    var_name: 'ALBOSE ( 84 NO ) ( DORANDO )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'DORANDO' }]
  },
  { name: ' ALBOSE (81 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC', 
  image: "/92.jpg", 
  rating: 4.8, 
  rate: 10, 
  CODE : 'GT-221',
  info:'GT-221 # ALBOSE ( 81 NO ) FIBER 4" BODY WITH FIBER RECIVE COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-221-BL', 
    var_name: 'ALBOSE ( 81 NO ) ( BLACK )', 
    var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-221-BR', 
    var_name: 'ALBOSE ( 81 NO ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-221-IV', 
    var_name: 'ALBOSE ( 81 NO ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-221-WT', 
    var_name: 'ALBOSE ( 81 NO ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-221-SI', 
    var_name: 'ALBOSE ( 81 NO ) ( SILVER )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-221-GL', 
    var_name: 'ALBOSE ( 81 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-221-DR', 
    var_name: 'ALBOSE ( 81 NO ) ( DORANDO )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: ' STAR LOCK (70 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC', 
  image: "/95.jpg", 
  rating: 4.8, 
  rate: 20, 
  CODE : 'GT-222',
  info:'GT-222 # STAR LOCK ( 70 NO ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-222-BL', 
    var_name: 'ALBOSE ( 70 NO ) ( BLACK )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-222-BR', 
    var_name: 'ALBOSE ( 70 NO ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-222-IV', 
    var_name: 'ALBOSE ( 70 NO ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-222-WT', 
    var_name: 'ALBOSE ( 70 NO ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-222-SI', 
    var_name: 'ALBOSE ( 70 NO ) ( SILVER )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-222-GL', 
    var_name: 'ALBOSE ( 70 NO ) ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-222-DR', 
    var_name: 'ALBOSE ( 70 NO ) ( DORANDO )', 
    var_img: '1.jpg',
      Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: ' STAR LOCK (61 NO )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC', 
  image: "/96.jpg", 
  rating: 4.8, 
  rate: 30, 
  CODE : 'GT-223',
  info:'GT-223 # STAR LOCK ( 61 NO ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO' , 
  variant: 
  [{ var_code: 'GT-223-BL',
  var_name: 'ALBOSE ( 61 NO ) ( BLACK )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'BLACK' },
   { var_code: 'GT-223-BR', 
   var_name: 'ALBOSE ( 61 NO ) ( BROWN )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'BROWN' },
   { var_code: 'GT-223-IV', 
   var_name: 'ALBOSE ( 61 NO ) ( IVORY )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'IVORY' },
   { var_code: 'GT-223-WT', 
   var_name: 'ALBOSE ( 61 NO ) ( WHITE )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'WHITE' },
   { var_code: 'GT-223-SI', 
   var_name: 'ALBOSE ( 61 NO ) ( SILVER )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'SILVER' },
   { var_code: 'GT-223-GL', 
   var_name: 'ALBOSE ( 61 NO ) ( GOLDEN )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'GOLDEN' },
   { var_code: 'GT-223-DR', 
   var_name: 'ALBOSE ( 61 NO ) ( DORANDO )', 
   var_img: '1.jpg',
    Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC',  
   var_color: 'DORANDO' }]
  },
  { name: ' AMERICAN HANDEL(6" )', 
  Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
MOQ: '200PC',
  image: "/97.jpg", 
  rating: 4.8, rate: 50, 
  CODE : 'GT-224',
  info:'GT-224 # AMERICAN HANDEL ( 6" ) FIBER 4" BODY WITH FIBER RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
  variant:[
    { var_code: 'GT-224-BL', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( BLACK )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-224-BR', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( BROWN )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'BROWN' },
    { var_code: 'GT-224-IV', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( IVORY )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'IVORY' },
    { var_code: 'GT-224-WT', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( WHITE )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'WHITE' },
    { var_code: 'GT-224-SI', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( SILVER )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'SILVER' },
    { var_code: 'GT-224-GL', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( GOLDEN )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'GOLDEN' },
    { var_code: 'GT-224-DR', 
    var_name: 'AMERICAN HANDEL ( 6" ) ( DORANDO )', 
    var_img: '1.jpg',
     Original_Price:'27.00', 
  Discounted_Price: '26.00', 
  var_total_price:'15200', 
  var_tdis_price: '14800',
var_moq: '200PC', 
    var_color: 'DORANDO' }]
  },
  {name: 'AMERICAN HANDEL ( 8" )',
  Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  MOQ: '720PC',
  image: '/49.jpg',
  rating: 4.7,rate: 15,
  CODE : 'GT-225',
   info: 'GT-225 # AMERICAN HANDEL ( 8" ) ALUMINUM 8" HANDEL COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO',
   variant: 
   [{ var_code: 'GT-225-BL',
   var_name: 'AMERICAN HANDEL ( 8" ) ( BLACK )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-225-BR', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'BROWN' },
    { var_code: 'GT-225-IV', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'IVORY' },
    { var_code: 'GT-225-WT', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'WHITE' },
    { var_code: 'GT-225-SI', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( SILVER )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'SILVER' },
    { var_code: 'GT-225-GL', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'GOLDEN' },
    { var_code: 'GT-225-DR', 
    var_name: 'AMERICAN HANDEL ( 8" ) ( DORANDO )', 
    var_img: '1.jpg',
      Original_Price: '26.00',
  Discounted_Price: '24.50',
 var_total_price:'15200', 
  var_tdis_price: '14800',  
  var_moq: '720PC', 
    var_color: 'DORANDO' }]
  },
  {name: 'DOMAL LOCK ( E-18 ) EAGLE', 
  Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
MOQ: '200PC', 
  image: '/50.jpg', 
  rating: 4.9,  rate: 30, 
  CODE : 'GT-226',
   info: 'GT-226 # DOMAL LOCK ( E-18 ) EAGLE 8" ALUMINUM CASTING WITH CASTING RECIVER AND S.S KNOB COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / GRAY ', 
   variant: 
   [{ var_code: 'GT-226-BL',
   var_name: 'DOMAL LOCK ( E-18 ) ( BLACK )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-226-BR', 
    var_name: 'DOMAL LOCK ( E-18 ) ( BROWN )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-226-IV', 
    var_name: 'DOMAL LOCK ( E-18 ) ( IVORY )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-226-WT', 
    var_name: 'DOMAL LOCK ( E-18 ) ( WHITE )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-226-SI', 
    var_name: 'DOMAL LOCK ( E-18 ) ( GRAY )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'GRAY' },
    { var_code: 'GT-226-GL', 
    var_name: 'DOMAL LOCK ( E-18 ) ( GOLDEN )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-226-DR', 
    var_name: 'DOMAL LOCK ( E-18 ) ( DORANDO )', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '85.00', 
  var_total_price:'17600', 
  var_tdis_price: '17000',
var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  { name: ' DOMAL LOCK ( E-18 ) EAGLE PRIMIUM',
  Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
MOQ: '200PC', 
  image: '/51.jpg', 
  rating: 4.8, rate: 25, 
  CODE : 'GT-227',
   info: 'GT-227 # DOMAL LOCK ( E-18 ) EAGLE PRIMIUM 8" ALUMINUM CASTING WITH CASTING RECIVER AND S.S KNOB COLOUR : BLACK / WHITE / GOLDEN / GRAY', 
   variant: 
    [{ var_code: 'GT-227-BL',
    var_name: 'DOMAL LOCK ( E-18 ) ( BLACK )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-227-BR', 
    var_name: 'DOMAL LOCK ( E-18 ) ( BROWN )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-227-IV', 
    var_name: 'DOMAL LOCK ( E-18 ) ( IVORY )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-227-WT', 
    var_name: 'DOMAL LOCK ( E-18 ) ( WHITE )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-227-SI', 
    var_name: 'DOMAL LOCK ( E-18 ) ( GRAY )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'GRAY' },
    { var_code: 'GT-227-GL', 
    var_name: 'DOMAL LOCK ( E-18 ) ( GOLDEN )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-227-DR', 
    var_name: 'DOMAL LOCK ( E-18 ) ( DORANDO )', 
    var_img: '1.jpg',
     Original_Price: '90.00', 
  Discounted_Price: '88.00', 
  var_total_price:'18000', 
  var_tdis_price: '17600',
var_moq: '200PC',  
    var_color: 'DORANDO' }]
  },
  {name: 'MINI DOMAL LOCK ( E-45 ) EAGLE', 
  Original_Price: '72.00', 
  Discounted_Price: '70.00', 
  var_total_price:'14400', 
  var_tdis_price: '14400',
MOQ: '200PC', 
  image: '/52.jpg', 
  rating: 4.7, rate: 20, 
  CODE : 'GT-228',
   info: 'GT-228 # MINI DOMAL LOCK ( E-45 ) EAGLE ALUMINUM 6" BODY WITH CASTING RECIVER RECIVER COLOUR : BLACK /  WHITE / GOLDEN ', 
   variant: 
   [{ var_code: 'GT-228-BL',
   var_name: 'MINI DOMAL LOCK ( BLACK )', 
    var_img: '1.jpg',
      Original_Price: '72.00', 
  Discounted_Price: '70.00', 
  var_total_price:'14400', 
  var_tdis_price: '14400',
var_moq: '200PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-228-WT', 
    var_name: 'MINI DOMAL LOCK ( WHITE )', 
    var_img: '1.jpg',
      Original_Price: '72.00', 
  Discounted_Price: '70.00', 
  var_total_price:'14400', 
  var_tdis_price: '14400',
var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-228-GL', 
    var_name: 'MINI DOMAL LOCK ( GOLDEN )', 
    var_img: '1.jpg',
      Original_Price: '72.00', 
  Discounted_Price: '70.00', 
  var_total_price:'14400', 
  var_tdis_price: '14400',
var_moq: '200PC',  
    var_color: 'GOLDEN' }]
  },
  { name: 'DOMAL LOCK WITH ( KEY )', 
  Original_Price: '230.00', 
  Discounted_Price: '220.00',
  var_total_price:'23000', 
  var_tdis_price: '22000',
MOQ: '100PC',
  image: '/53.jpg', 
  rating: 4.9, 
  rate: 40,
  CODE : 'GT-229', 
  info: 'GT-229 # DOMAL LOCK WITH ( KEY )  8" ALUMINUM CASTING WITH CASTING RECIVER AND S.S KNOB COLOUR : BLACK / WHITE / GOLDEN / ', 
  variant: 
  [{ var_code: 'GT-229-BL',
  var_name: 'DOMAL LOCK ( KEY ) ( BLACK )', 
   var_img: '1.jpg',
   Original_Price: '230.00', 
  Discounted_Price: '220.00',
  var_total_price:'23000', 
  var_tdis_price: '22000',
var_moq: '100PC', 
   var_color: 'BLACK' },
   { var_code: 'GT-229-WT', 
   var_name: 'DOMAL LOCK ( KEY ) ( WHITE )', 
   var_img: '1.jpg',
   Original_Price: '230.00', 
  Discounted_Price: '220.00',
  var_total_price:'23000', 
  var_tdis_price: '22000',
var_moq: '100PC', 
   var_color: 'WHITE' },
   { var_code: 'GT-229-GL', 
   var_name: 'DOMAL LOCK ( KEY ) ( GOLDEN )', 
   var_img: '1.jpg',
   Original_Price: '230.00', 
  Discounted_Price: '220.00',
  var_total_price:'23000', 
  var_tdis_price: '22000',
var_moq: '100PC', 
   var_color: 'GOLDEN' }]
  },
  {name: 'DOMAL LOCK ( ALUMINIUM CASTING ) 0.130 GRAM',
  Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  MOQ: '200PC', 
  image: '/54.jpg',
  rating: 4.8,
  rate: 35,
  CODE : 'GT-230', 
  info: 'GT-230 #  DOMAL LOCK ( ALUMINUM CASTING ) 8" ALUMINUM CASTING WITH CASTING RECIVER AND S.S KNOB COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / GRAY',
  variant: [
    { var_code: 'GT-230-BL', 
    var_name: 'DOMAL LOCK ( ALUMINIUM ) ( 8" ) ( BLACK )', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'BLACK' },
    { var_code: 'GT-230-BR', 
    var_name: 'DOMAL LOCK ( ALUMINIUM ) ( 8" ) ( BROWN )', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'BROWN' },
    { var_code: 'GT-230-IV',
    var_name: 'DOMAL LOCK ( ALUMINIUM ) ( 8" ) ( IVORY )', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'IVORY' },
    { var_code: 'GT-230-WT',
    var_name: 'DOMAL LOCK ( ALUMINIUM ) ( 8" ) ( WHITE )', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'WHITE' },
    { var_code: 'GT-230-SI', 
    var_name: 'DOMAL LOCK (ALUMINIUM)(8")(SILVER)', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'SILVER' },
    { var_code: 'GT-230-GL', 
    var_name: 'DOMAL LOCK (ALUMINIUM)(8")(GOLDEN)', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'GOLDEN' },
    { var_code: 'GT-230-DR',
    var_name: 'DOMAL LOCK (ALUMINIUM)(8")(DORANDO)', 
    var_img: '1.jpg',
      Original_Price: '83.00',
  Discounted_Price: '78.00',
 var_total_price:'16600', 
  var_tdis_price: '15600',  
  var_moq: '200PC',  
    var_color: 'DORANDO' }
  ]
  },
  {name: 'DOMAL LOCK ( ZINK CASTING ) 0.175 GRAM',
  Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  MOQ: '200 PC',
  image: '/55.jpg', 
  rating: 4.9, 
  rate: 25, 
  CODE : 'GT-231', 
  info: 'GT-231 # DOMAL LOCK ( ZINK CASTING ) ALUMINUM 6" BODY WITH CASTING RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / GRAY', 
  variant:[
    { var_code: 'GT-231-BL', 
    var_name: 'DOMAL LOCK (ZINK CASTING)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'BLACK' },
    { var_code: 'GT-231-WT', 
    var_name: 'DOMAL LOCK (ZINK CASTING)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'WHITE' },
    { var_code: 'GT-231-GL', 
    var_name: 'DOMAL LOCK (ZINK CASTING)(GOLDEN)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'GOLDEN' },
    { var_code: 'GT-231-IV', 
    var_name: 'DOMAL LOCK (ZINK CASTING)',
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'IVORY' },
    { var_code: 'GT-231-BR', 
    var_name: 'DOMAL LOCK (ZINK CASTING)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'BROWN' },
    { var_code: 'GT-231-SI', 
    var_name: 'DOMAL LOCK (ZINK CASTING)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'SILVER' },
    { var_code: 'GT-231-GR', 
    var_name: 'DOMAL LOCK (ZINK CASTING)(GREY)', 
    var_img: '1.jpg',
     Original_Price: '88.00', 
  Discounted_Price: '83.00',
 var_total_price:'17600', 
  var_tdis_price: '16600',  
  var_moq: '200 PC', 
    var_color: 'GREY' }
  ]
  },
   {name: 'DOMAL DIAMOND LOCK', 
   Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
  var_tdis_price: '27000',   
  MOQ: '200 PC',  
  image: '/56.jpg', 
   rating: 4.7, 
   rate: 20, 
   CODE : 'GT-232', 
   info: 'GT-232 # DOMAL DIAMOND LOCK 8" ALUMINUM CASTING WITH CASTING RECIVER AND S.S KNOB   COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / GRAY', 
   variant:  [
    { var_code: 'GT-232-BL', 
    var_name: ' DOMAL LOCK(DAIMOND)', 
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'BLACK' },
     { var_code: 'GT-232-BR', 
    var_name: 'DOMAL LOCK(DAIMOND)', 
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'BROWN' },
    { var_code: 'GT-232-WT', 
    var_name: ' DOMAL LOCK(DAIMOND)', 
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'WHITE' },
    { var_code: 'GT-232-GL', 
    var_name: ' DOMAL LOCK(DAIMOND)', 
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'GOLDEN' },
    { var_code: 'GT-232-IV',
    var_name: ' DOMAL LOCK(DAIMOND)', 
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'IVORY', },
    { var_code: 'GT-232-GR', 
    var_name: ' DOMAL LOCK(DAIMOND)',
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'GREY' },
    { var_code: 'GT-232-DR', 
    var_name: ' DOMAL LOCK(DAIMOND)',
    var_img: '1.jpg',
    var_moq:'200 PC',
    Original_Price: '140.00', 
   Discounted_Price: '13500',
    var_total_price:'28000', 
    var_tdis_price: '27000', 
    var_color: 'DORANDO' }
  ]
  },
   { name: 'SAILESH LOCK 4"',
   Original_Price: '30.00',
   Discounted_Price: '28.50',
 var_total_price:'2000', 
  var_tdis_price: '1000',   
  MOQ: '480 PC',  image: '/57.jpg',
   rating: 4.8, 
   rate: 35,
   CODE : 'GT-233', 
   info: '8" ALUMINUM BODY WITH CASTING RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO',
   variant:[
    { var_code: 'GT-233-DR', 
    var_name: 'SAILESH LOCK 4', 
    var_img: '1.jpg',
    var_moq:'480',
    Original_Price: '30.00',
   Discounted_Price: '28.50',
    var_total_price:'14400', 
    var_tdis_price: '13680', 
    var_color: 'DORANDO' 
   }, 
  { var_code: 'GT-233-SI', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'SILVER' 
  },
  { var_code: 'GT-233-BL', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'BLACK' },
  { var_code: 'GT-233-BR', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'BROWN' },
  { var_code: 'GT-233-WT', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'WHITE' },
  { var_code: 'GT-233-GL', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'GOLDEN' },
  { var_code: 'GT-233-IV', 
  var_name: 'SAILESH LOCK 4', 
  var_img: '1.jpg',
  var_moq:'480',
  Original_Price: '30.00',
   Discounted_Price: '28.50',
  var_total_price:'14400', 
  var_tdis_price: '13680', 
  var_color: 'IVORY' }]
},
   { name: 'SAILESH LOCK ( 6" )', 
    Original_Price: '57.00', 
    Discounted_Price: '55.00', 
    var_total_price:'13680', 
      var_tdis_price: '13200',
MOQ: '240 PC', 
image: '/58.jpg', 
    rating: 4.7, 
    rate: 10, 
    CODE : 'GT-234', 
    info: ' ALUMINUM BODY WITH METAL RECIVER COLOUR : BLACK / BROWN / WHITE / GOLDEN / IVORY / SILVER / DORANDO', 
    variant:[
      { var_code: 'GT-234-BL', 
      var_name: 'SAILESH LOCK ( 6" )', 
      var_img: '1.jpg',
      var_moq:'240PC',
      var_total_price:'13680', 
      var_tdis_price: '13200', 
      var_color: 'BLACK' 
    },
    { var_code: 'GT-234-BR', 
    var_name: 'SAILESH LOCK ( 6" )', 
    var_img: '1.jpg',
    var_moq:'240PC' ,
    Original_Price: '57.00', 
    Discounted_Price: '55.00', 
    var_total_price:'13680', 
    var_tdis_price: '13200', 
    var_color: 'BROWN' 
    },
    { var_code: 'GT-234-SI', 
      var_name: 'SAILESH LOCK ( 6" )', 
      var_img: '1.jpg',
      var_moq:'240PC' ,
      Original_Price: '57.00', 
    Discounted_Price: '55.00', 
      var_total_price:'13680', 
      var_tdis_price: '13200', 
      var_color: 'SILVER' 
    },
    { var_code: 'GT-234-WT', 
      var_name: 'SAILESH LOCK ( 6" )', 
      var_img: '1.jpg',
      var_moq:'240PC',
      Original_Price: '57.00', 
    Discounted_Price: '55.00', 
      var_total_price:'13680',
      var_tdis_price: '13200', 
      var_color: 'WHITE' 
    },
    { var_code: 'GT-234-GL', 
    var_name: 'SAILESH LOCK ( 6" )', 
    var_img: '1.jpg',
    var_moq:'240PC',
    Original_Price: '57.00', 
    Discounted_Price: '55.00', 
    var_total_price:'13680', 
    var_tdis_price: '13200', 
    var_color: 'GOLDEN' 
    }, 
    { var_code: 'GT-234-IV', 
    var_name: 'SAILESH LOCK ( 6" )', 
    var_img: '1.jpg',
    var_moq:'240PC' ,
    Original_Price: '57.00', 
    Discounted_Price: '55.00', 
    var_total_price:'13680', 
    var_tdis_price: '13200', 
    var_color: 'IVORY' 
    },
    { var_code: 'GT-234-DR', 
    var_name: 'SAILESH LOCK ( 6" )', 
    var_img: '1.jpg',
    var_moq:'240PC' ,
    Original_Price: '57.00', 
    Discounted_Price: '55.00', 
    var_total_price:'13680', 
    var_tdis_price: '13200',
    var_color: 'DORANDO' 
    }]
}
  ]

  const itemsPerPage = 6;
  function VariantImage({ image, selected, onClick, variant }) {
    return (
      <div className={`variant-item ${selected ? 'selected' : ''}`} onClick={onClick}>
        <img src={image} alt="Variant" />
        {selected && variant && (
          <div className="variant-info">
            <p className="description-text">Color: <br/>{variant.var_color}</p>
            <p className="description-text">Code: <br/>{variant.var_code}</p>
            <p className="description-text">Name:<br/> {variant.var_name}</p>
            <p className="description-text">Total-price:<br/> {variant.var_total_price}</p>
            <p className="description-text">Total-Discount:<br/> {variant.var_tdis_price}</p>
          </div>
        )}
      </div>
    );
  }
  
function ConcealLock() {
  const [activePage, setActivePage] = useState(1);
  const [showModal, setShowModal] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const { addToQuote, addVariantToQuote } = useQuote();

  const totalPages = Math.ceil(products.length / itemsPerPage);
  const startIndex = (activePage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentPageData = products.slice(startIndex, endIndex);
  const [isLoggedIn, setIsLoggedIn] = useState(false); // Example state for authentication status

  const [selectedVariant, setSelectedVariant] = useState(null);

  const [quantity, setQuantity] = useState(1);

  const [alertMessage, setAlertMessage] = useState('');
  const [showAlert, setShowAlert] = useState(false);
  const [activeIndex, setActiveIndex] = useState(0);

  const handleNext = () => {
    setActiveIndex((prevIndex) => (prevIndex + 1) % selectedProduct.variant.length);
  };
  
  const handlePrev = () => {
    setActiveIndex((prevIndex) =>
      prevIndex === 0 ? selectedProduct.variant.length - 1 : prevIndex - 1
    );
  };

  const handleCloseAlert = () => {
    setShowAlert(false);
  };

  const loginPrompt = () => {
    alert('Please log in to add items to the cart');
    // You can replace this alert with your actual login prompt logic, such as displaying a modal or redirecting to the login page
  };


  const paginationItems = [];
  for (let number = 1; number <= totalPages; number++) {
    paginationItems.push(
      <Pagination.Item
        key={number}
        active={number === activePage}
        onClick={() => setActivePage(number)}
      >
        {number}
      </Pagination.Item>,
    );
  }
  const handleShowModal = (product, variant) => {
    setShowModal(true);
    setSelectedProduct(product);
    setSelectedVariant(variant);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setSelectedProduct(null); // Set selectedProduct to null explicitly
    setSelectedVariant(null); // Also set selectedVariant to null
  };

  const handleAddToCart = (product) => {
    addToQuote(product,quantity);
  setAlertMessage(`${product.name} added to get Quotes`);
  setShowAlert(true);
  };

const handlevariantAddToCart = (variant) => {
  // addToQuote(variant); // Add the selected variant to the cart
  addVariantToQuote(variant,quantity); // Add the selected variant to the cart
  setSelectedVariant(variant); // Set the selected variant in context
  setAlertMessage(`${variant.var_name} added to get Quotes`);
  setShowAlert(true);
  // toast.success(`${variant.var_name} added to get Quotes`, { // Display variant name in toast
  //   position: "bottom-right",
  //   autoClose: 3000,
  //   hideProgressBar: false,
  //   closeOnClick: true,
  //   pauseOnHover: true,
  //   draggable: true,
  // });
};

// const [quantity, setQuantity] = useState(1);

const handleQuantityChange = (e) => {
  setQuantity(parseInt(e.target.value));
};
  return (
    <section id="product" className="block product-block"
     style={{paddingTop:'125px'}}
     >
 <Container fluid>
        <Row>
          <Col>
            <Alert
              show={showAlert}
              variant="success"
              onClose={handleCloseAlert}
              dismissible
            >
              {alertMessage}
            </Alert>
          </Col>
        </Row>
      </Container>

      <Container fluid>
        <Row className='portfoliolist' style={{padding: '1.2rem'}}>
          {currentPageData.map((product, index) => (
            <Col sm={4} key={index}>
              <div className='portfolio-wrapper'>
                <div>
                  <Image src={product.image} onClick={() => handleShowModal(product)} />
                  <div className='label text-center'>
  <h6>{product.name}</h6>
  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
  <div style={{ display: 'flex', alignItems: 'center' }}>
  <p style={{ marginRight: '10px' }}>MOQ: {product.MOQ}</p>
  <div className="input-container">
        <input
          className="quantity-input"
          type="number"
          value={quantity}
          onChange={handleQuantityChange}
        />
      </div>
</div>

    {/* <div style={{ display: 'flex', alignItems: 'center' }}>
    <p className="rate" style={{color:'red', textDecoration:'line-through', marginRight: '10px'}}>{product.Original_Price} </p>
      <p className="rate"> {product.Discounted_Price}</p>
      <FaMoneyBill className="money-icon" />
    </div> */}

    <div style={{ display: 'flex', alignItems: 'center' }}>
    <p className="rate" style={{color:'red', textDecoration:'line-through', marginRight: '10px'}}>{product.var_total_price} </p>
      <p className="rate"> {product.var_tdis_price}</p>
      <FaMoneyBill className="money-icon" />
    </div>
    
  </div>
  <div>
    <button style={{borderRadius:'0px'}} className="learn-more-button" onClick={() => handleAddToCart(product)}>
      Add To Cart
    </button>
  </div>
</div>
</div>
</div>
  </Col>
          ))}
        </Row>

        <Pagination>{paginationItems}</Pagination>
      </Container>

<section className='prodinfo' >
  
      <Modal show={showModal} onHide={handleCloseModal} dialogClassName="custom-modal product-details-modal" >
      <Container fluid>
        <Row>
          <Col>
            <Alert  show={showAlert} variant="success" onClose={handleCloseAlert} dismissible style={{ fontSize: '0.8rem'}}>
              {alertMessage}
            </Alert>
          </Col>
        </Row>
      </Container>
        <Modal.Header closeButton>
          <Modal.Title> 
            <Navbar.Brand as={Link} to="/">
            <img src={Logo} alt="Logo" height="50" className="d-inline-block align-top mr-3" />
          </Navbar.Brand>
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
        <Row className="productcard" style={{ height: 'auto' }}>
  <Col xs={12} md={5} className="photo">
    <Image src={selectedVariant ? selectedVariant.var_img : (selectedProduct && selectedProduct.image)} />
    {selectedVariant && (
    <Col xs={12} md={5} className="selected-variant-info">
       {/* <h6>{selectedVariant.var_name}</h6> */}
      <p>Color: {selectedVariant.var_color}</p>
      <p>Code: {selectedVariant.var_code}</p>
      <div className="input-container">
        <input
          className="quantity-input"
          type="number"
          value={quantity}
          onChange={handleQuantityChange}
        />
      </div>
    </Col>
  )}
  </Col>
  <Col xs={12} md={7} className="description">
    <h5>{selectedProduct && selectedProduct.name}</h5>
    <h6>Product Code: {selectedProduct && selectedProduct.CODE}</h6>
    <p>DESCRIPTION<br />{selectedProduct && selectedProduct.info}</p>
    <p>{`M.O.Q: ${selectedProduct && selectedProduct.MOQ}`}</p>
    <h3>                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      Price Per Item:{" "}
      <span style={{ textDecoration: 'line-through', color: 'red', fontSize: '13px' }}>
        {selectedProduct && selectedProduct.Original_Price} INR
      </span>
      <Row className="variant-images">
        {selectedProduct &&
          selectedProduct.variant.map((variant, index) => (
            <Col xs={1} key={index} className="variant-item">
              <img
                style={{ width: '62px', height: '62px', marginTop: '5px'}}
                src={variant.var_img}
                alt={variant.var_name}
                onClick={() => handleShowModal(selectedProduct, variant)}
              />
              {/* <p className='var_name'>{variant.var_code}</p> */}
            </Col>
          ))}
      </Row>
      <span style={{ fontSize: '13px' }}> {selectedProduct && selectedProduct.Discounted_Price} INR</span>
    </h3>
    {/* <Button 
    // className="add-cart-btn"
    className="learn-more-button"
     onClick={() => handlevariantAddToCart(selectedVariant)}>
                    Add to Cart
                  </Button> */}

<Button
  className="learn-more-button"
  onClick={() => {
    if (!selectedVariant || selectedVariant.var_code === selectedProduct.CODE) {
      handleAddToCart(selectedProduct);
    } else {
      handlevariantAddToCart(selectedVariant);
    }
  }}
>
  {!selectedVariant || selectedVariant.var_code === selectedProduct.CODE
    ? 'Add To Cart'
    : 'Add to Cart'}
</Button>

  </Col>
 
</Row>

  
</Modal.Body>


        
      </Modal>
      </section>
      {/* <ToastContainer /> */}

      {/* <Alert
  show={showAlert}
  variant="success"
  onClose={handleCloseAlert}
  dismissible
>
  {alertMessage}
</Alert> */}

{/* 
<Container fluid>
        <Row>
          <Col>
            <Alert
              show={showAlert}
              variant="success"
              onClose={handleCloseAlert}
              dismissible
            >
              {alertMessage}
            </Alert>
          </Col>
        </Row>
      </Container> */}
    </section>
  );
}

export default ConcealLock;